### ISSUE TITLE
Unable to retrieve detailed reports.

### ISSUE THREAD

**Issue by miloszsobiczewski** [mwegrzynek/litex.regon#3]
Unable to retrieve detailed reports for following regons:
`api.search(regons="01210292600037,01210292600051,01210292600076", detailed=True)`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../lib/python3.6/site-packages/litex/regon/__init__.py", line 230, in search
    correct_report_name
  File "/Users/.../lib/python3.6/site-packages/litex/regon/__init__.py", line 257, in full_report
    )[0]
IndexError: list index out of range
```

**Comment by mwegrzynek** [comment]
regons param should be a list of strings, not a comma delimited string. Try
``` api.search(regons=["01210292600037","01210292600051","01210292600076"], detailed=True). 
 ```

**Comment by miloszsobiczewski** [comment]
Yes, you are right regarding the invocation, sorry about that, but it is not the case. The problem is for above regons `correct_report_name` is not returning any data, that is why I'm getting the error here
```        result = objectify.fromstring(
            get_message_element(
                mesg,
                0,
                '//bir:DanePobierzPelnyRaportResult/text()'
            )[0]
        )
```
in fact `extended_report_name` does.
Please find my fork, I made a dummy fix for that.

**Comment by mwegrzynek** [comment]
Hi! sorry for long delay and thanks for reporting. Could you please test the `pytest` branch? Also, don't hesitate to create a pull request next time :)
