### ISSUE TITLE
Getting data from lxml object python

### ISSUE THREAD

**Issue by wiktoriapanek** [mwegrzynek/litex.regon#8]
Hi!

Do you have any idea of how can I get data from this object?
I got a response (below) and have no clue what to do next.

element = api.search(regon='931931108')
element

**[<Element dane at 0x124bd98c0>]**

type(element) = list

**Comment by mwegrzynek** [comment]
Hi!

please take a look [here](https://lxml.de/tutorial.html) and in the documentation you got from the REGON administrators.  For example, this will get you REGON of your result stored in the `element` variable:

```
element[0].Regon
```

**Comment by wiktoriapanek** [comment]
Hello!

Thank you so much for helping me, it solved my problem :)
Have a nice day.

With best regards
Wiktoria Panek

pt., 5 lis 2021 o 14:16 Michał Węgrzynek ***@***.***>
napisał(a):
